version: '3'
services:
  mongo:
    image: mongo:latest
  java-app:
    build: .
    environment:
      - spring.data.mongodb.host=mongo
      - spring.data.mongodb.port=27017
    ports:
      - 8080:8080